server:
  port: 8081
  context-path: /isv

eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      version: 1.0.0.0
      weight: 100

spring:
  application:
    name: isv-srv
  profiles:
    active: dev
  messages:
    basename: i18n/messages,i18n/errors
  jackson:
    default-property-inclusion: non_null

  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 1
      min-idle: 1
      max-active: 5
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false

mybatis:
  mapper-locations: classpath*:mybatis/mapper/**/*.xml
  config-locations: classpath*:mybatis/config.xml

logging:
    path: ./logs/isv

disconf:
  app: ISV
  nation: ph
  forceOverwriteUserProperties: true

feign:
  producer:
    path: trade
  hystrix:
    enabled: false
  httpclient:
    enabled: true
  okhttp:
    enabled: false

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  eureka:
    enabled: true

swagger:
  title: trade api
  version: 1.8

management:
  port: 54321
  security:
    enabled: false

address:
  ip:
    port: